# Generated by Django 5.1.5 on 2025-01-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(related_name='blogs', to='blog.blogcategory'),
        ),
    ]
