# Generated by Django 4.2.18 on 2025-01-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_education_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('logo', models.ImageField(upload_to='')),
                ('body', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=250)),
            ],
        ),
    ]
