# Generated by Django 5.1.5 on 2025-01-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_service_skill_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
