# Generated by Django 4.2.18 on 2025-01-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
