# Generated by Django 4.2.18 on 2025-06-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_history', models.PositiveIntegerField()),
                ('completed_projects', models.PositiveIntegerField()),
                ('satisfaction_rate', models.FloatField()),
                ('years_os_experience', models.PositiveIntegerField()),
            ],
        ),
    ]
